server:
  port: 8080

spring:
  application:
    name: spring-boot-template-7
  # mariadb datasource 지정
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 311029
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
# jpa:     hibernate:       ddl-auto: update  SQL 쿼리 로그            
logging:
  level:
    org.hibernate.SQL: debug